# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'clipR' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNTextDetector', path: '../node_modules/react-native-text-detector/ios'

  target 'clipRTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
